version: '2.3'
services:
  app:
    image: local/dl_remote:latest
    container_name: dl_remote
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
    - $HOME/.mujoco/mjkey.txt/:/root/.mujoco/mjkey.txt
    - $HOME/docker/ipython:/root/.ipython
    - $HOME/docker/workspace:/root/workspace
    working_dir: /root
    ports:
      - 6006:6006
      - 5900:5900
      - 8888:8888
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: |-
      bash -xc '
      /root/start.sh
      DISPLAY=:0 jupyter lab --ip 0.0.0.0 --port 8888 --allow-root --NotebookApp.token='' --NotebookApp.password=''
      '